#Draft of something to be generated by the config file

def dicer():
	import random
	return random.randint(1,6) + random.randint(1,6)

config = {
	'types': ["lumber", "ore", "wool"],
	'dicer': dicer
}